
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from ui.cifrado import cifradoUi
from ui.desifrado import desifrarUi
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
def cifradoFun(parent):
    parent.destroy()
    cifradoUi()
def desifrarFun(parent):
    parent.destroy()
    desifrarUi()
def inicioUi():
    OUTPUT_PATH = Path(__file__).parent
    ASSETS_PATH = OUTPUT_PATH / Path(r"./assets/frame0")

    def relative_to_assets(path: str) -> Path:
        return ASSETS_PATH / Path(path)

    window = Tk()
    window.geometry("565x319")
    window.configure(bg="#4D93FB")

    canvas = Canvas(
        window,
        bg="#4D93FB",
        height=319,
        width=565,
        bd=0,
        highlightthickness=0,
        relief="ridge"
    )
    canvas.place(x=0, y=0)
    canvas.create_text(
        22.0,
        32.0,
        anchor="nw",
        text="Sistema de Hash (MATEMATICA)",
        fill="#FFFFFF",
        font=("Inter Bold", 24 * -1)
    )

    image_image_1 = PhotoImage(file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(282.0, 159.0, image=image_image_1)

    btnDecifrar = PhotoImage(file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=btnDecifrar,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: desifrarFun(window),
        relief="flat"
    )
    button_1.place(x=228.0, y=149.0, width=107.0, height=35.0)

    btnCifrar = PhotoImage(file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=btnCifrar,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: cifradoFun(window),
        relief="flat"
    )
    button_2.place(x=240.0, y=105.0, width=83.0, height=35.0)

    button_image_3 = PhotoImage(file=relative_to_assets("button_3.png"))
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_3 clicked"),
        relief="flat"
    )
    button_3.place(x=466.0, y=266.0, width=83.0, height=35.0)

    window.resizable(False, False)
    window.mainloop()